name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@dev
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /task-likho/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: master # The branch the action should deploy to.
        build_folder: dist/task-likho # The folder where your project is supposed to be after running ng build by the action.
